# Generated by Django 4.1.5 on 2023-01-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskslist", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
