# Generated by Django 4.1.5 on 2023-01-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskslist", "0003_alter_task_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tag",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="taskslist.tag"),
        ),
    ]
